In [1]:
import numpy as np

In [3]:
x = np.array([1.0, 2.0, 3.0])

In [4]:
type(x)

numpy.ndarray

In [7]:
y = np.array([2.0, 4.0, 6.0])

In [8]:
x+y

array([3., 6., 9.])

In [9]:
x-y

array([-1., -2., -3.])

In [10]:
x*y

array([ 2.,  8., 18.])

In [11]:
x/y

array([0.5, 0.5, 0.5])

In [12]:
x/2

array([0.5, 1. , 1.5])

In [13]:
A = np.array([[1,2],
              [3,4]])

In [14]:
A.dtype

dtype('int32')

In [16]:
B = np.array([[3, 0],
              [0, 6]])

In [18]:
A+B

array([[ 4,  2],
       [ 3, 10]])

In [19]:
A*B

array([[ 3,  0],
       [ 0, 24]])

In [20]:
B = np.array([10, 20])

In [25]:
A*B

array([[10, 40],
       [30, 80]])

In [24]:
A*B.reshape(2,1)

array([[10, 20],
       [60, 80]])

In [27]:
A+B

array([[11, 22],
       [13, 24]])

In [26]:
A+B.reshape(2,1)

array([[11, 12],
       [23, 24]])

In [28]:
A[0]

array([1, 2])

In [29]:
for row in A:
    print(row)

[1 2]
[3 4]


In [30]:
import matplotlib.pyplot as plt

In [31]:
x = np.arange(0, 6, 0.1)
y = np.sin(x)

In [ ]:
plt.plot(x, y)
plt.show()