In [1]:
import numpy as np

In [4]:
x = np.array([-1.0, 1.0, 2.0])
y = x > 0
y.astype(int)

array([0, 1, 1])

In [5]:
A = np.array([1, 2, 3, 4])
print(A)

[1 2 3 4]


In [6]:
np.ndim(A)

1

In [7]:
A.shape

(4,)

In [9]:
B = np.array([[1,2],
              [3,4],
              [5,6]])

In [10]:
np.ndim(B)

2

In [11]:
B.shape

(3, 2)

In [12]:
A = np.array([[1,2],
              [3,4]])
B = np.array([[5,6],
              [7,8]])

In [17]:
A*B

array([[ 5, 12],
       [21, 32]])

In [14]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [18]:
np.dot(B,A)

array([[23, 34],
       [31, 46]])

In [19]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[1,2],
              [3,4],
              [5,6]])

In [20]:
np.dot(A,B)

array([[22, 28],
       [49, 64]])

In [21]:
np.dot(B,A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [22]:
C = np.array([[1,2],
              [3,4]])

In [25]:
np.dot(C,A)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [26]:
D = np.array([7,8])

In [28]:
np.dot(B,D)

array([23, 53, 83])

In [29]:
# like neural network
X = np.array([1,2])
W = np.array([[1,3,5],
              [2,4,6]])
print(W)

[[1 3 5]
 [2 4 6]]


In [30]:
Y = np.dot(X, W)

In [31]:
Y

array([ 5, 11, 17])

In [32]:
print(Y)

[ 5 11 17]
