In [1]:
import os
import numpy as np 

In [3]:
# ordinary softmax
a = np.array([0.3, 2.9, 4.0])
a_exp = np.exp(a)
print(a_exp)

In [7]:
sum_a_exp = np.sum(a_exp)
print(sum_a_exp)

In [9]:
y = a_exp / sum_a_exp

In [11]:
# softmax example
print(y)

[0.01821127 0.24519181 0.73659691]


In [12]:
def softmax(val):
    val_exp = np.exp(val)
    sum_val_exp = np.sum(val_exp)
    y = val_exp / sum_val_exp
    return(y)

In [14]:
# modified softmax
a = np.array([1010, 1000, 990])
np.exp(a) / np.sum(np.exp(a))

c:\users\haenm\anaconda3\envs\bt\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until
c:\users\haenm\anaconda3\envs\bt\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan, nan, nan])

In [15]:
C = np.max(a)

In [16]:
a-C

array([  0, -10, -20])

In [19]:
np.exp(a-C)/np.sum(np.exp(a-C))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [20]:
np.sum(np.exp(a-C)/np.sum(np.exp(a-C)))

1.0

In [21]:
def softmax(val):
    C = np.max(val)
    exp_val = np.exp(val-C)
    y = exp_val / np.sum(exp_val)
    return(y)